### ISSUE TITLE
[meta] CSS Value Definition Syntax issues

### ISSUE THREAD

**Issue by tidoust** [w3c/reffy#110]
Here is a list of issues found while trying to extract CSS value definitions from CSS specs. Most of them are editorial in essence, some may be due to misreading (or reading too much into) the [Value Definition Syntax](https://drafts.csswg.org/css-values/#value-defs):

- [x] [css-backgrounds] Use of `&nbsp;` in [Bikeshed source](https://github.com/w3c/csswg-drafts/blob/master/css-backgrounds-3/Overview.bs#L1597) for "Applies to" and "Computed value" headers makes columns appear twice in [property index](https://drafts.csswg.org/css-backgrounds/#property-index) (see w3c/csswg-drafts#2911)
- [x] [css-rhythm] Missing quotes around property refs in [`block-step` dfn](https://drafts.csswg.org/css-rhythm/#block-step) (see w3c/csswg-drafts#2912)
- [x] [css-shapes] Missing quotes around property ref in [`polygon()` dfn](https://drafts.csswg.org/css-shapes-1/#funcdef-polygon) (see w3c/csswg-drafts#2912)
- [x] [css-shapes] Missing quotes around property ref in [`path()` dfn](https://drafts.csswg.org/css-shapes-2/#funcdef-path) (see w3c/csswg-drafts#2912)
- [x] [css-flexbox] Missing quotes around property refs in [`flex-flow` dfn](https://drafts.csswg.org/css-flexbox/#propdef-flex-flow) (see w3c/csswg-drafts#2912)
- [x] [css-ui] Missing quotes around property refs in [`outline` dfn](https://drafts.csswg.org/css-ui-4/#propdef-outline) (see w3c/csswg-drafts#2912)
- [x] [css-align] Missing quotes around property refs in [`place-items` dfn](https://drafts.csswg.org/css-align/#propdef-place-items) (see w3c/csswg-drafts#2912)
- [x] [css-overflow] Missing quotes around property ref in [`line-clamp` dfn](https://drafts.csswg.org/css-overflow/#propdef-line-clamp) (see w3c/csswg-drafts#2912)
- [x] [fill-stroke] Missing quotes around property ref in [`fill` dfn](https://drafts.fxtf.org/fill-stroke/#propdef-fill) (see w3c/fxtf-drafts#300)
- [x] [fill-stroke] The [`fill` dfn](https://drafts.fxtf.org/fill-stroke/#propdef-fill) is actual prose, not a string that follows the Value Definition Syntax. (see w3c/fxtf-drafts#300)
- [ ] [filter-effects] [`<url>`](https://drafts.fxtf.org/filter-effects/#typedef-filter-url) should rather link to the [real `<url>` dfn](https://drafts.csswg.org/css-values-4/#url-value) (see w3c/fxtf-drafts#301)
- [x] [svg-markers] `compound-selector` should be `<compound-selector>` in the [`<child-selector>` dfn]( https://svgwg.org/specs/markers/#DataTypeChildSelector) (see w3c/svgwg#498)
- [x] [css-grid] The [`<track-repeat>` dfn](https://drafts.csswg.org/css-grid/#typedef-track-repeat) references `<positive-integer>`, which is not defined in any CSS spec (see w3c/csswg-drafts#355)
- [x] [css-fonts] Missing quotes around `{` and `}` in [`<feature-value-block>` dfn](https://drafts.csswg.org/css-fonts-4/#font-feature-values-syntax) (see w3c/csswg-drafts#2915)
- [x] [css-backgrounds] The [`border-color` dfn](https://drafts.csswg.org/css-backgrounds-4/#propdef-border-color) value should probably be `[<color>{1,4}]#` instead of `(<color>{1,4})#` (see w3c/csswg-drafts#2916)
- [x] [css-backgrounds] In the [`border-color` dfn](https://drafts.csswg.org/css-backgrounds-4/#propdef-border-color), the "Value" header should link to `https://drafts.csswg.org/css-values/#value-defs` (see w3c/csswg-drafts#2916)
- [x] [css-backgrounds] New values for [`background-clip`](https://drafts.csswg.org/css-backgrounds-4/#background-clip) should use `|` to separate values as in other specs (see w3c/csswg-drafts#2916)
- [x] [css-grid] Not clear how to intepret the [`repeat` dfn](https://drafts.csswg.org/css-grid-2/#typedef-name-repeat). Does `[ | auto-fill ]` mean an empty value is allowed? What does the `+` apply to? Shouldn't it be a `#` (without comma)? (see w3c/csswg-drafts#2917)
- [x] [css-tables] The `border-spacing` dfn value has zero-width spaces around `length`, see (well, with an hex editor, otherwise you won't see much) the [corresponding line in source file](https://github.com/w3c/csswg-drafts/blob/master/css-tables-3/Overview.bs#L803)) which make the value invalid per the Value Definition Syntax. (see w3c/csswg-drafts#2918)
- [ ] [css-gcpm] The term [`content-list`](https://drafts.csswg.org/css-gcpm-4/#content-list) should rather be `content-level` to match the prose, and should probably be `<content-level>` to match conventions used in other CSS specs (see w3c/csswg-drafts#2919)
- [x] [compositing] No easy way to tell that the [`<blend-mode>` dfn](https://drafts.fxtf.org/compositing-1/#ltblendmodegt) is a production rule. Other specs have a `css` class. (see w3c/fxtf-drafts#302)
- [x] [svg] No easy way to tell that the [`<dasharray>` dfn](https://svgwg.org/svg2-draft/painting.html#DataTypeDasharray) is a production rule. Other specs have a `css` class. (see w3c/svgwg#499)
- [x] [css-fonts] The value of the [`src` descriptor](https://drafts.csswg.org/css-fonts-4/#descdef-font-face-src) should not be "see prose" but rather a string that follows the Value Definition Syntax. It was defined with such a string in [Level 3](https://drafts.csswg.org/css-fonts/#descdef-src). Is that no longer doable? (see w3c/csswg-drafts#2920)
- [ ] [css-values] Keyword values do not allow for some of the values used in specs. The syntax says that [keyword values](https://drafts.csswg.org/css-values/#component-types) are [identifiers](https://drafts.csswg.org/css-values/#identifier) and as such conform to the `<ident-token>` grammar, which does not allow values to start with a digit or an `@`. However, some values need that such as [`glyph-orientation-vertical`](https://drafts.csswg.org/css-writing-modes-4/#propdef-glyph-orientation-vertical), [`font-weight`](https://drafts.csswg.org/css-fonts-3/#font-weight-prop) (although replaced by `<number>` in Level 4), or [`@stylistic`](https://drafts.csswg.org/css-fonts-4/) (see w3c/csswg-drafts#2921)
- [ ] [css-values] Definition equations are not defined in the [Value Definition Syntax](https://drafts.csswg.org/css-values/#value-defs). In other words, the use of `=`, and the description of how to read the left-side seems to be missing. For non-terminals, most specs use `<non-terminal-name> = <dfn>` equations, but `<>` are sometimes omitted on the left-side as in the [`inset()` dfn](https://drafts.csswg.org/css-shapes-1/#funcdef-inset) and [`content-list` dfn](https://drafts.csswg.org/css-gcpm-4/#content-list), or there may be no `=` sign as in the [`fade()` dfn](https://drafts.csswg.org/css-overflow-4/#funcdef-text-overflow-fade). Also, some definitions use a final semi-colon as in [CSS Display](https://drafts.csswg.org/css-display/#typedef-display-outside), [CSS Box Alignment](https://drafts.csswg.org/css-align/#typedef-content-position) and [CSS Counter Styles](https://drafts.csswg.org/css-counter-styles/#typedef-counter-style), but most don't. (see w3c/csswg-drafts#2921)
- [ ] [css-syntax] Dagger characters are not allowed by the Value Definition Syntax in the [`<an+b>` dfn](https://drafts.csswg.org/css-syntax-3/#the-anb-type) (see w3c/csswg-drafts#2921)
- [ ] [bikeshed] Curly quotes should not replace single quotes in dfn values, as done in [`flex` dfn](https://drafts.csswg.org/css-flexbox/#propdef-flex), since grammar does not allow for it. (see w3c/csswg-drafts#2921)

**Comment by dontcallmedom** [comment]
I've updated the list of items to be checked off; I haven't deteremined which subset of https://github.com/w3c/csswg-drafts/issues/2921 still needs to be done.

I noted that  [it was suggested](https://github.com/w3c/csswg-drafts/issues/2921#issuecomment-406417129) we bring the ["missing rules" list](https://github.com/tidoust/reffy/blob/master/src/specs/missing-css-rules.json) as a separate github issue - @tidoust, do you know if we ever did that? (the list might need an update too)

**Comment by tidoust** [comment]
> I noted that it was suggested we bring the "missing rules" list as a separate github issue - @tidoust, do you know if we ever did that? (the list might need an update too)

No, I think that is still a TODO.

**Comment by tidoust** [comment]
Closing the issue as now outdated. CSS syntax issues are tracked separately, and Strudy would be the right place to collect anomalies.
